### ISSUE TITLE
Request: grouping by multiple properties

### ISSUE THREAD

**Issue by Jogai** [vdolek/sharp-collections#11]
I want to group by multiple properties, I'm used to do this in linq (example runnable in linqpad):

	Enumerable.Range(0,5).Select(x=> new { Name = new String((char)(65+x), 5), Wheels = x%2*2+2, Doors = x%2*4+2 })
	.GroupBy(x => new {x.Wheels, x.Doors}) 
	.SelectMany(y => y.Select(z => $"Key (Wheels/Doors): {y.Key.Wheels}/{y.Key.Doors} | Object: {z.Name}/{z.Wheels}/{z.Doors}"))

Line 2 is what I want to do in typescript. Line 3 is just to demonstrate what linq returns as a result. I wouldn't mind having no key accessible. This outputs for me:

    Key (Wheels/Doors): 2/2 | Object: AAAAA/2/2
    Key (Wheels/Doors): 2/2 | Object: CCCCC/2/2
    Key (Wheels/Doors): 2/2 | Object: EEEEE/2/2
    Key (Wheels/Doors): 4/6 | Object: BBBBB/4/6
    Key (Wheels/Doors): 4/6 | Object: DDDDD/4/6

In this case, two arrays containing an array of 3 and 2 objects would be good enough for me.

**Comment by vdolek** [comment]
Currently `groupBy` does not support objects and `EqualityComparer`. Only solution I can think of right now is somehow concatenate values in keySelector of groupBy method.

```typescript
Enumerable.range(0, 5)
  .select(x => {
    return {
      name: Enumerable.repeat(String.fromCharCode(65 + x), 5).toArray().join(''),
      wheels: x%2*2+2,
      doors: x%2*4+2
    };
  })
  .groupBy(x => `${x.wheels}/${x.doors}`)
  .selectMany(y => y.select(z => `Key (Wheels/Doors): ${y.key} | Object: ${z.name}/${z.wheels}/${z.doors}`))
```

Try it here: https://stackblitz.com/edit/sharp-collections-playground-euricd

I will try to add support of `EqualityComparer` for keys in `groupBy` method.

**Comment by vdolek** [comment]
In version 1.7.1 has been added support for `EqualityComparer` in `groupBy` method. Shallow and deep `EqualityComparer` has been added too (`EqualityComparer.shallow()`, `EqualityComparer.deep()`).

You can achieve what you want by this:

```typescript
Enumerable.range(0, 5)
  .select(x => ({
      name: Enumerable.repeat(String.fromCharCode(65 + x), 5).toArray().join(''),
      wheels: x%2*2+2,
      doors: x%2*4+2
  }))
  .groupBy(x => ({ wheels: x.wheels, doors: x.doors }), EqualityComparer.shallow())
  .selectMany(y => y.select(z => `Key (Wheels/Doors): ${y.key.wheels}/${y.key.doors} | Object: ${z.name}/${z.wheels}/${z.doors}`))
```

Try it here: https://stackblitz.com/edit/sharp-collections-playground-issue-11-v2

**Comment by Jogai** [comment]
Awesome, works as expected!
