### ISSUE TITLE
Uncaught ReferenceError: global is not defined in Angular 11

### ISSUE THREAD

**Issue by aligin** [vdolek/sharp-collections#14]
Hello. I've found this wonderful library as the replace of custom "distinct", "groupBy", "select" and other our favourite linq techniques. Bus as I mentioned in the title in blank angular 11 project there is an error in the console "Uncaught ReferenceError: global is not defined". There are several similar errors in other libraries that uses in Angular and the Angular team suggests to add `(window as any).global = window;` in polyfills.ts as the temporary solution. But I think maybe there is any methods to not using global in the library sharp-collections itself?

**Comment by vdolek** [comment]
Please try preview version [`1.7.2-next.0`](https://www.npmjs.com/package/sharp-collections/v/1.7.2-next.0) and let me know if it solves the issue.

**Comment by aligin** [comment]
It works! Thanks a lot!

**Comment by vdolek** [comment]
Fixed in version [`1.7.3`](https://www.npmjs.com/package/sharp-collections/v/1.7.3).

**Comment by vdolek** [comment]
I am glad you like the library. If you have ony other problem or proposal do not hesitate to file an issue or contact me.
