### ISSUE TITLE
Example is off by one

### ISSUE THREAD

**Issue by Jogai** [vdolek/sharp-collections#8]
5 entries in data, but the total of the groups (2+2)=4

**Comment by vdolek** [comment]
The example works as expected. Notice using `adults` variable with `groupBy` not the `enumerable` nor `data` variable.

```typescript
const data = [
  { name: 'Martin', sex: 'M', age: 28 },
  { name: 'Jane', sex: 'F', age: 27 },
  { name: 'Thomas', sex: 'M', age: 15 },
  { name: 'William', sex: 'M', age: 78 },
  { name: 'Kelly', sex: 'F', age: 30 },
]; // here is indeed 5 items

const enumerable = Enumerable.from(data);

const adults = enumerable.where(x => x.age >= 18); // this line filters data and produces enumerable of 4 items
const adultsGroupedBySex = adults.groupBy(x => x.sex); // this groups items in two groups, both of size 2
```

**Comment by vdolek** [comment]
Thanks for the interest for this library. If you have any other question, do not hesitate to ask by e-mail. Or file an issue if you find a bug or to propose new features.

**Comment by Jogai** [comment]
Oh thanks :facepalm: 

Thank you for replying so fast!
